[package]
name = "MLP"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
rand = "0.8.5"
ndarray = "0.16.1"
rand_distr = "0.4.3"

[lib]
name = "mlp"
crate-type = ["lib"]
